version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: studentReview
    ports:
      - 5432:5432
    volumes:
      - ./:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

